import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], // Commented out autogenerated sidebar

  // Create a sidebar manually
  docsSidebar: [ // Renamed from tutorialSidebar for clarity
    {
      type: 'doc',
      id: 'release-notes', // Links to docs/docs/release-notes.md
    },
    {
      type: 'doc',
      id: 'admin-cms-guide', // Links to docs/docs/admin-cms-guide.md
    },
    {
      type: 'doc',
      id: 'example-page', // Links to docs/docs/example-page.md
    },
    // Add more docs or categories here later
    // Example:
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   items: ['another-doc'],
    // },
  ],
};

export default sidebars;
